#!/usr/bin/env python3
"""
Generate parameterized hierarchical CRDT topologies for scaling tests.

Supports:
  - Plan A: Single ContainerLab topology up to ~1,015 nodes (under 1,023 bridge limit)
  - Plan B: Dual ContainerLab topologies split across two bridges with ~597 nodes each

Usage:
  # Plan A: 1,015 nodes (7 companies x 4 platoons x 4 squads x 9/squad)
  python3 generate-scaling-topology.py --companies 7 --name lab-1000n

  # Plan A: Custom sizing
  python3 generate-scaling-topology.py --companies 3 --platoons 4 --squads 4 --soldiers 8 --name lab-custom

  # Plan B: Split across two bridges (8 companies, 4 per bridge)
  python3 generate-scaling-topology.py --companies 8 --split --name peat-1200 --subnet-a 172.30.0.0/22 --subnet-b 172.31.0.0/22

  # Dry run: just print node count
  python3 generate-scaling-topology.py --companies 7 --dry-run
"""

import argparse
import sys
from typing import TextIO


def compute_node_count(companies: int, platoons: int, squads: int, soldiers: int) -> dict:
    """Compute total nodes for given hierarchy parameters."""
    soldiers_total = companies * platoons * squads * soldiers
    squad_leaders = companies * platoons * squads
    platoon_leaders = companies * platoons
    company_commanders = companies
    battalion_hq = 1
    total = soldiers_total + squad_leaders + platoon_leaders + company_commanders + battalion_hq
    return {
        "soldiers": soldiers_total,
        "squad_leaders": squad_leaders,
        "platoon_leaders": platoon_leaders,
        "company_commanders": company_commanders,
        "battalion_hq": battalion_hq,
        "total": total,
    }


def write_header(f: TextIO, name: str, counts: dict, companies: int, platoons: int,
                 squads: int, soldiers: int, subnet: str = "172.30.0.0/20") -> None:
    """Write YAML header with topology metadata."""
    f.write(f"""# Hierarchical Peat CRDT Scaling Topology: {name}
# Total nodes: {counts['total']}
# Structure: {companies} companies x {platoons} platoons x {squads} squads x {soldiers} soldiers
# + {counts['squad_leaders']} squad leaders + {counts['platoon_leaders']} platoon leaders + {companies} company COs + 1 battalion HQ
# Generated by generate-scaling-topology.py

name: {name}

mgmt:
  network: {name}
  ipv4-subnet: {subnet}

topology:
  nodes:
""")


def write_node(f: TextIO, node_id: str, role: str, node_type: str,
               unit_id_key: str, unit_id_val: str, tcp_listen: int,
               tcp_connect: str | None, lab_name: str,
               squad_members: str | None = None,
               wait_for_start: bool = True) -> None:
    """Write a single node definition."""
    f.write(f"""    {node_id}:
      kind: linux
      image: peat-sim-node:latest
      env:
        NODE_ID: {node_id}
        ROLE: {role}
        PLATFORM_TYPE: soldier
        NODE_TYPE: {node_type}
        MODE: hierarchical
        BACKEND: ${{BACKEND}}
        {unit_id_key}: {unit_id_val}
""")
    if squad_members:
        f.write(f"        SQUAD_MEMBERS: \"{squad_members}\"\n")
    f.write(f"""        UPDATE_RATE_MS: "5000"
        TCP_LISTEN: "{tcp_listen}"
""")
    if tcp_connect:
        f.write(f"        TCP_CONNECT: \"{tcp_connect}\"\n")
    f.write(f"""        PEAT_APP_ID: ${{PEAT_APP_ID}}
        PEAT_OFFLINE_TOKEN: ${{PEAT_OFFLINE_TOKEN}}
        PEAT_SHARED_KEY: ${{PEAT_SHARED_KEY}}
        CIRCUIT_FAILURE_THRESHOLD: "3"
        CIRCUIT_FAILURE_WINDOW_SECS: "2"
        CIRCUIT_OPEN_TIMEOUT_SECS: "2"
        CIRCUIT_SUCCESS_THRESHOLD: "2"
""")
    if wait_for_start:
        f.write("""        WAIT_FOR_START: "true"
""")
    f.write("\n")


def generate_topology(f: TextIO, lab_name: str, companies_range: range,
                      platoons: int, squads: int, soldiers: int,
                      base_port: int, subnet: str,
                      hq_connect: str | None = None,
                      include_hq: bool = True,
                      wait_for_start: bool = True) -> int:
    """Generate a complete topology for a set of companies.

    Returns the next available port number.
    """
    port = base_port
    all_companies = list(companies_range)

    counts = {
        "soldiers": len(all_companies) * platoons * squads * soldiers,
        "squad_leaders": len(all_companies) * platoons * squads,
        "platoon_leaders": len(all_companies) * platoons,
        "company_commanders": len(all_companies),
        "battalion_hq": 1 if include_hq else 0,
        "total": (len(all_companies) * platoons * squads * soldiers +
                  len(all_companies) * platoons * squads +
                  len(all_companies) * platoons +
                  len(all_companies) +
                  (1 if include_hq else 0)),
    }

    write_header(f, lab_name, counts, len(all_companies), platoons, squads, soldiers, subnet)

    # Battalion HQ
    hq_port = port
    if include_hq:
        write_node(f, "battalion-hq", "battalion_commander", "battalion_commander",
                   "BATTALION_ID", "battalion-1", port, None, lab_name,
                   wait_for_start=wait_for_start)
        port += 1

    # Companies
    for c in all_companies:
        co_port = port
        co_id = f"company-{c}-commander"
        # Company commander connects to battalion HQ
        if hq_connect:
            # Cross-bridge: use provided IP-based connection
            co_connect = hq_connect
        elif include_hq:
            co_connect = f"clab-{lab_name}-battalion-hq:{hq_port}"
        else:
            co_connect = None

        f.write(f"    # ===== COMPANY {c} =====\n\n")
        write_node(f, co_id, "company_commander", "company_commander",
                   "COMPANY_ID", f"company-{c}", port, co_connect, lab_name,
                   wait_for_start=wait_for_start)
        port += 1

        for p in range(1, platoons + 1):
            pl_port = port
            pl_id = f"company-{c}-platoon-{p}-leader"
            pl_connect = f"clab-{lab_name}-{co_id}:{co_port}"

            f.write(f"    # ----- Platoon {c}-{p} -----\n\n")
            write_node(f, pl_id, "platoon_leader", "platoon_leader",
                       "PLATOON_ID", f"company-{c}-platoon-{p}", port,
                       pl_connect, lab_name, wait_for_start=wait_for_start)
            port += 1

            for s in range(1, squads + 1):
                sl_port = port
                sl_id = f"company-{c}-platoon-{p}-squad-{s}-leader"
                sl_connect = f"clab-{lab_name}-{pl_id}:{pl_port}"

                # Build squad members list
                members = [
                    f"company-{c}-platoon-{p}-squad-{s}-soldier-{i}"
                    for i in range(1, soldiers + 1)
                ]
                squad_members_str = ",".join(members)

                write_node(f, sl_id, "squad_leader", "squad_leader",
                           "SQUAD_ID", f"company-{c}-platoon-{p}-squad-{s}",
                           port, sl_connect, lab_name,
                           squad_members=squad_members_str,
                           wait_for_start=wait_for_start)
                port += 1

                for i in range(1, soldiers + 1):
                    sold_id = f"company-{c}-platoon-{p}-squad-{s}-soldier-{i}"
                    sold_connect = f"clab-{lab_name}-{sl_id}:{sl_port}"

                    write_node(f, sold_id, "soldier", "soldier",
                               "SQUAD_ID", f"company-{c}-platoon-{p}-squad-{s}",
                               port, sold_connect, lab_name,
                               wait_for_start=wait_for_start)
                    port += 1

    return port


def generate_single(args: argparse.Namespace) -> None:
    """Generate a single ContainerLab topology (Plan A)."""
    output = f"{args.name}-1gbps.yaml"
    with open(output, 'w') as f:
        generate_topology(
            f, args.name,
            companies_range=range(1, args.companies + 1),
            platoons=args.platoons,
            squads=args.squads,
            soldiers=args.soldiers,
            base_port=12345,
            subnet=args.subnet_a,
            wait_for_start=args.wait_for_start,
        )
    print(f"  Generated: {output}")


def generate_split(args: argparse.Namespace) -> None:
    """Generate dual ContainerLab topologies (Plan B)."""
    if args.companies < 2:
        print("ERROR: --split requires at least 2 companies", file=sys.stderr)
        sys.exit(1)

    split_point = args.companies // 2
    name_a = f"{args.name}-a"
    name_b = f"{args.name}-b"

    # Bridge A: companies 1..split_point + battalion HQ
    output_a = f"{name_a}-1gbps.yaml"
    with open(output_a, 'w') as f:
        generate_topology(
            f, name_a,
            companies_range=range(1, split_point + 1),
            platoons=args.platoons,
            squads=args.squads,
            soldiers=args.soldiers,
            base_port=12345,
            subnet=args.subnet_a,
            include_hq=True,
            wait_for_start=args.wait_for_start,
        )
    print(f"  Generated: {output_a}")

    # Bridge B: companies (split_point+1)..N, no HQ
    # Cross-bridge connection placeholder — will be injected by deployment script
    # For now, use a placeholder that the deploy script replaces with the actual IP
    hq_connect = "__CROSS_BRIDGE_HQ_ADDR__:12345"

    output_b = f"{name_b}-1gbps.yaml"
    with open(output_b, 'w') as f:
        generate_topology(
            f, name_b,
            companies_range=range(split_point + 1, args.companies + 1),
            platoons=args.platoons,
            squads=args.squads,
            soldiers=args.soldiers,
            base_port=12345,
            subnet=args.subnet_b,
            include_hq=False,
            hq_connect=hq_connect,
            wait_for_start=args.wait_for_start,
        )
    print(f"  Generated: {output_b}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate parameterized hierarchical CRDT topologies for scaling tests",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Plan A: 1,015 nodes (7 companies, under 1,023 bridge limit)
  %(prog)s --companies 7 --name lab-1000n

  # Plan B: Dual bridge, 8 companies split 4+4
  %(prog)s --companies 8 --split --name peat-1200

  # Dry run to check node count
  %(prog)s --companies 7 --dry-run
""",
    )
    parser.add_argument("--companies", type=int, default=7,
                        help="Number of companies (default: 7)")
    parser.add_argument("--platoons", type=int, default=4,
                        help="Platoons per company (default: 4)")
    parser.add_argument("--squads", type=int, default=4,
                        help="Squads per platoon (default: 4)")
    parser.add_argument("--soldiers", type=int, default=8,
                        help="Soldiers per squad (default: 8)")
    parser.add_argument("--name", type=str, default="lab-1000n",
                        help="Topology name prefix (default: lab-1000n)")
    parser.add_argument("--split", action="store_true",
                        help="Generate dual-bridge split topology (Plan B)")
    parser.add_argument("--subnet-a", type=str, default="172.30.0.0/20",
                        help="Management subnet for bridge A (default: 172.30.0.0/20)")
    parser.add_argument("--subnet-b", type=str, default="172.31.0.0/20",
                        help="Management subnet for bridge B (default: 172.31.0.0/20)")
    parser.add_argument("--wait-for-start", action="store_true", default=True,
                        help="Enable WAIT_FOR_START on all nodes (default: true)")
    parser.add_argument("--no-wait-for-start", action="store_false", dest="wait_for_start",
                        help="Disable WAIT_FOR_START")
    parser.add_argument("--dry-run", action="store_true",
                        help="Just print node count, don't generate files")

    args = parser.parse_args()

    counts = compute_node_count(args.companies, args.platoons, args.squads, args.soldiers)

    print(f"Hierarchy: {args.companies} companies x {args.platoons} platoons x {args.squads} squads x {args.soldiers} soldiers")
    print(f"  Battalion HQ:        {counts['battalion_hq']}")
    print(f"  Company commanders:  {counts['company_commanders']}")
    print(f"  Platoon leaders:     {counts['platoon_leaders']}")
    print(f"  Squad leaders:       {counts['squad_leaders']}")
    print(f"  Soldiers:            {counts['soldiers']}")
    print(f"  TOTAL:               {counts['total']}")

    if not args.split and counts['total'] > 1023:
        print(f"\n  WARNING: {counts['total']} nodes exceeds 1,023 bridge limit!")
        print("  Consider using --split for dual-bridge deployment.")

    if args.split:
        split_point = args.companies // 2
        counts_a = compute_node_count(split_point, args.platoons, args.squads, args.soldiers)
        counts_b = compute_node_count(args.companies - split_point, args.platoons, args.squads, args.soldiers)
        # Bridge B doesn't have its own HQ
        counts_b["total"] -= 1
        counts_b["battalion_hq"] = 0
        print(f"\n  Split: Bridge A = {counts_a['total']} nodes, Bridge B = {counts_b['total']} nodes")
        if counts_a['total'] > 1023 or counts_b['total'] > 1023:
            print(f"  ERROR: Bridge exceeds 1,023 limit! Adjust company split.")
            sys.exit(1)

    if args.dry_run:
        return

    print()

    if args.split:
        generate_split(args)
    else:
        generate_single(args)

    print("\nDone!")


if __name__ == "__main__":
    main()
